=== hpepper/idea-to-product/sad2md/test/software_architecture_documentation.dtd
<!-- Version: 0.1.0 -->
<!-- validate xml: clear; xmllint -valid  itp.xml  > t 2>u; head u -->
<!-- the '-valid' actually has a double '-' in front but dtd can't have that. -->
<!ELEMENT SoftwareArchitectureDocumentation (
  Title,
  Issue,
  Revision,
  Draft,
  Status,
  ReleaseDate,
  Author,
  Summary,
  ViewPacket+,
  Component+,
  ComponentRelation*
)>
<!ATTLIST SoftwareArchitectureDocumentation Version CDATA #REQUIRED>

<!ELEMENT Author (#PCDATA)>
<!ELEMENT Draft (#PCDATA)>
<!ELEMENT Issue (#PCDATA)>
<!ELEMENT ReleaseDate (#PCDATA)>
<!ELEMENT Revision (#PCDATA)>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT Summary (#PCDATA)>
<!ELEMENT Title (#PCDATA)>

<!ELEMENT ViewPacket (
  Title?,
  ComponentRecurseLevel?,
  Introduction,
  ContextModelKey?,
  ComponentId+,
  ContextModelKey?,
  DiagramKey*,
  ParentViewPacketId*,
  ChildViewPacketId*,
  SiblingViewPacketId*
)>
<!ATTLIST ViewPacket Id CDATA #REQUIRED>
<!ATTLIST ViewPacket ViewType  CDATA #REQUIRED>
<!ATTLIST ViewPacket ViewStyle  CDATA #REQUIRED>
<!ATTLIST ViewPacket SortOrder  CDATA #REQUIRED>

<!ELEMENT  ComponentRecurseLevel (#PCDATA)>
<!ELEMENT  Introduction (#PCDATA)>
<!ELEMENT  ComponentId (#PCDATA)>
<!ELEMENT  ContextModelKey (#PCDATA)>
<!ELEMENT  ParentViewPacketId (#PCDATA)>
<!ELEMENT  ChildViewPacketId (#PCDATA)>
<!ELEMENT  SiblingViewPacketId (#PCDATA)>

<!ELEMENT Component (
  Summary,
  Responsibilities?,
  BehaviorDescription?,
  VisibilityOfInterfaces?,
  Interface?,
  License*,
  SourceRepository*,
  ArtifactRepository*,
  File*,
  BuildCycle?,
  Contact*,
  TestInformation?,
  ImplementationConstraints?,
  Performance*,
  Capacity?,
  Reliability?,
  ResourceRequirement?,
  Functionality?,
  Security?,
  SchedulerPriority?,
  DiagramKey*,
  ArchitectureDecisionId*
)>
<!ATTLIST Component Id CDATA #REQUIRED>
<!ATTLIST Component Name CDATA #REQUIRED>

<!ELEMENT BehaviorDescription  (#PCDATA)>
<!ELEMENT Responsibilities  (#PCDATA)>
<!ELEMENT VisibilityOfInterfaces  (#PCDATA)>
<!ELEMENT Interface  (#PCDATA)>
<!ELEMENT Overview  (#PCDATA)>
<!ELEMENT BuildCycle  (#PCDATA)>
<!ELEMENT Contact  (#PCDATA)>
<!ELEMENT License  (#PCDATA)>
<!ELEMENT SourceRepository  (#PCDATA)>
<!ELEMENT ArtifactRepository  (#PCDATA)>
<!ELEMENT File  (#PCDATA)>
<!ELEMENT TestInformation  (#PCDATA)>
<!ELEMENT ImplementationConstraints  (#PCDATA)>
<!ELEMENT  Performance (#PCDATA)>
<!ELEMENT  Capacity (#PCDATA)>
<!ELEMENT  Reliability (#PCDATA)>
<!ELEMENT  ResourceRequirement (#PCDATA)>
<!ELEMENT  Functionality (#PCDATA)>
<!ELEMENT  Security (#PCDATA)>
<!ELEMENT  SchedulerPriority (#PCDATA)>
<!ELEMENT  DiagramKey (#PCDATA)>
<!ATTLIST  DiagramKey StyleType  CDATA #IMPLIED>
<!ELEMENT  ArchitectureDecisionId (#PCDATA)>

<!ELEMENT ComponentRelation (
  ComponentAId,
  ComponentBId,
  Key,
  PropertiesOfRelation
)>
<!ATTLIST ComponentRelation Id CDATA #REQUIRED>

<!ELEMENT ComponentAId  (#PCDATA)>
<!ELEMENT ComponentBId  (#PCDATA)>
<!ELEMENT Key  (#PCDATA)>
<!ELEMENT PropertiesOfRelation  (#PCDATA)>

=== hpepper/idea-to-product/sad2md/test/test_sad.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE SoftwareArchitectureDocumentation SYSTEM "software_architecture_documentation.dtd">

<SoftwareArchitectureDocumentation Version="0.1.0">
  <Title>SW Arcitechture Documentation for ITP"</Title>
  <Issue>0.1.0</Issue>
  <Revision>0.1.0</Revision>
  <Draft>1</Draft>
  <Status></Status>
  <ReleaseDate></ReleaseDate>
  <Author></Author>
  <Summary></Summary>

  <ViewPacket Id="1" ViewType="Module" ViewStyle="Decomposition" SortOrder="1">
    <Title>Viking conflict game</Title>
    <Introduction>An online card battle game.</Introduction>
    <ContextModelKey>ContextDiagram001</ContextModelKey>
    <ComponentId>1</ComponentId>
    <DiagramKey>Decomposition001</DiagramKey>
  </ViewPacket>

  <ViewPacket Id="2" ViewType="Module" ViewStyle="Decomposition" SortOrder="2">
    <Title>Game server</Title>
    <Introduction></Introduction>
    <ContextModelKey>ContextDiagram002</ContextModelKey>
    <ComponentId>2</ComponentId>
    <DiagramKey>Decomposition002</DiagramKey>
  </ViewPacket>

  <Component Id="1" Name="Viking clonflict game">
    <Summary></Summary>
    <Responsibilities></Responsibilities>
  </Component>

  <Component Id="2" Name="server">
    <Summary></Summary>
    <Responsibilities></Responsibilities>
  </Component>

  <Component Id="3" Name="client">
    <Summary></Summary>
    <Responsibilities></Responsibilities>
  </Component>

<ComponentRelation Id="1">
  <ComponentAId>1</ComponentAId>
  <ComponentBId>2</ComponentBId>
  <Key>Decomposition001</Key>
  <PropertiesOfRelation></PropertiesOfRelation>
</ComponentRelation>

<ComponentRelation Id="2">
  <ComponentAId>1</ComponentAId>
  <ComponentBId>3</ComponentBId>
  <Key>Decomposition001</Key>
  <PropertiesOfRelation></PropertiesOfRelation>
</ComponentRelation>

<ComponentRelation Id="3">
  <ComponentAId>1</ComponentAId>
  <ComponentBId>4</ComponentBId>
  <Key>ContextDiagram001</Key>
  <PropertiesOfRelation></PropertiesOfRelation>
</ComponentRelation>

<!-- The ComponentAId is 'The Work' in a context diagram. -->
<ComponentRelation Id="4">
  <ComponentAId>1</ComponentAId>
  <ComponentBId>5</ComponentBId>
  <Key>ContextDiagram001</Key>
  <PropertiesOfRelation></PropertiesOfRelation>
</ComponentRelation>

</SoftwareArchitectureDocumentation>
